<?xml version="1.0" encoding="UTF-8"?>
<testrun name="TeacherTest.test" project="hibernate_0104_HelloWorld" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testcase name="test" classname="com.bjsxt.hibernate.model.TeacherTest" time="0.082">
    <error>org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update&#13;
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:94)&#13;
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)&#13;
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:275)&#13;
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:266)&#13;
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:167)&#13;
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)&#13;
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)&#13;
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1028)&#13;
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:366)&#13;
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:137)&#13;
	at com.bjsxt.hibernate.model.TeacherTest.test(TeacherTest.java:30)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&#13;
	at java.lang.reflect.Method.invoke(Method.java:597)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)&#13;
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.sql.BatchUpdateException: Duplicate entry '2' for key 'PRIMARY'&#13;
	at com.mysql.jdbc.ServerPreparedStatement.executeBatch(ServerPreparedStatement.java:648)&#13;
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)&#13;
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)&#13;
	... 33 more&#13;
&#13;
</error>
  </testcase>
</testrun>
